<?php

/**
 * CustomobjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomobjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomobjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Customobject');
    }
}