<?php

/**
 * SimobjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SimobjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SimobjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Simobject');
    }
}